### ISSUE TITLE
Save account information via SQLite database.

### ISSUE THREAD

**Issue by rainy-seasons** [uwu-bot/steamboat#2]
Saving the users accounts and passwords should be done through a local SQLite database. Passwords should be encrypted / hashed+salted.

**Comment by xyx0826** [comment]
Handling plaintext credential is not a good idea. But if we hash the password, we cannot retrieve plaintext anymore. This is probably not helpful to saving Steam logins.

#5 minimizes plaintext password exposure in managed code and implements encryption/decryption based on Windows DPAPI. Passwords are encrypted with an `entropy` (IV) then stored in `base64` together with its `IV`.

**Comment by rainy-seasons** [comment]
Ah, I see. Nice, merged. 👍

**Comment by wilsonvargas** [comment]
Pls check my PR #7 I've solved this issue. 🐱‍👤🐱‍👤
