### ISSUE TITLE
Documentation needed.

### ISSUE THREAD

**Issue by rainy-seasons** [uwu-bot/steamboat#3]
Currently there is no documentation at all.

**Comment by theshahulhameed** [comment]
Can you give a brief idea about the project so that I can help you on the same?

**Comment by rainy-seasons** [comment]
Sure. It's for switching between steam accounts easily. You add accounts, save them, then you should be able to just double click an account on the list and automatically login to it. Eventually, there might be other features such as managing config files for each profile easier, things like that. The accounts will ideally be stored in a local SQLite database with passwords encrypted.

It's still in the early stages, however.

**Comment by theshahulhameed** [comment]
Okay, I can help with the documentation part of the project.
