### ISSUE TITLE
Editing existing account entry doesn't work.

### ISSUE THREAD

**Issue by rainy-seasons** [uwu-bot/steamboat#8]
Attempting to edit an existing account in the listbox doesn't edit the account details. It leaves it unchanged. It should be updated to whatever is entered in the textboxes. The password should remain unchanged unless the user changes it, currently it is replaced by a "fake password" (12345678), this should not overwrite the password if the user doesn't change it.

**Comment by AbhiAgarwal192** [comment]
@uwu-bot Created Pull Request for the fix.
